name: Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [ "16.x" ]
    runs-on: ubuntu-latest
    steps:
      - name: Start NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-verison }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Depedencies
        run: npm install

      - name: Run Migration
        run: npm run migrate
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy App
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}