name: Build, lint and run all tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: ["14.x"]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_DB: farmlend
          POSTGRES_PASSWORD: password
          # set up health check for postgres
        options: --health-cmd pg_isready --health-interval 10ms --health-timeout 500ms --health-retries 15

    steps:
      - name: Start NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Run Integration Tests
        run: npm run test:e2e
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: admin
          DB_PASSWORD: password
          DB_NAME: farmlend
